"""rename address

Revision ID: 954f09d1e496
Revises: 1a9bfccbf9d3
Create Date: 2025-06-13 22:52:29.206849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '954f09d1e496'
down_revision = '1a9bfccbf9d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('location', sa.String(), nullable=False))
    op.drop_column('departments', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('address', sa.VARCHAR(), nullable=True))
    op.drop_column('departments', 'location')
    # ### end Alembic commands ###
